Modes added

diff --git a/mess_cleaner b/mess_cleaner
--- a/mess_cleaner
+++ b/mess_cleaner
@@ -1,15 +1,31 @@
-#!/usr/bin/zsh
+#!/usr/bin/env zsh
 
 usage() {
-	echo "Usage: $0 -c (class name) -f (file to rename)"
+	echo "mess-cleaner usage:"
+	echo "\t-c\t Class to add to the file name"
+	echo "\t-f\t File to rename"
+	echo "\t-h\t Displays this message\n"
 }
 
-CONFIG_FILE="modules.conf"
+echoerr() {
+	echo "$@" 1>&2
+}
+
+# This makes the script exit if a command fails
+set -o errexit
+# Avoids expressions like 'error here | true' to be executed
+set -o pipefail
+# List all executed lines. Usefull for debugging
+#set -o xtrace
+
+readonly CONFIG_FILE="modules.conf"
 
 class=""
 file=""
+# Default mode is: rename file and create a directory
+mode=1
 
-while getopts "c:f:h" option; do
+while getopts "c:f:hm:" option; do
 	case "$option" in
 		c)
 			class=$OPTARG
@@ -19,15 +35,20 @@ while getopts "c:f:h" option; do
 			;;
 		h)
 			usage
+			exit 0
+			;;
+		m)
+			mode=$OPTARG
 			;;
 		*)
 			usage
+			exit 1
 			;;
 	esac
 done
 
 if [[ -z "$class" || -z "$file" ]]; then
-	echo "Missing options!"
+	echoerr "Missing options!\n"
 	usage
 	exit 1
 fi
@@ -35,13 +56,25 @@ fi
 grep $class $CONFIG_FILE -n > /dev/null
 
 if [ $? -eq 1 ]; then
-	echo "$class does not exist"
+	echoerr "$class does not exist!"
+	exit 1
+fi
+
+if [ ! -f "$file" ]; then
+	echoerr "File does not exit!"
+	exit 1
+fi
+
+if [[ ! $mode =~ '^[1-3]$' ]]; then
+	echoerr "The mode you entered is not valid"
+	echoerr "Enter a mode between 1 and 3"
 	exit 1
 fi
 
 class_name="INFO"
 class_name+=$(grep $class $CONFIG_FILE -n | cut -f1 -d:)
 
+# Removes all the unwanted characters
 base_name=$(perl -pe "s/^.*(?=(_[psPS]_))//g;" -pe "s/(_f)?(_v[0-9{2}][a-z]?)?//g" <<< "$file")
 
 file_name="$class_name"
@@ -51,9 +84,21 @@ file_name+="$base_name"
 
 directory_name=$(perl -pe "s/^.*(?=([0-9]{4}))//g;" -pe "s/\..*$//g" <<< "$base_name")
 
-mkdir "$directory_name"
-mv $file $file_name
-
-mv $file_name $directory_name
+case "$mode" in
+	1)
+		mkdir "$directory_name"
+		mv $file $file_name
+		mv $file_name $directory_name
+		;;
+	2)
+		mv $file $file_name
+		;;
+	3)
+		mkdir "$directory_name"
+		mv $file $directory_name
+		;;
+	*)
+		;;
+esac
 
 exit 0
