Implement verbose mode

diff --git a/mess-cleaner b/mess-cleaner
--- a/mess-cleaner
+++ b/mess-cleaner
@@ -1,5 +1,20 @@
 #!/usr/bin/env zsh
 
+. $HOME/dev/shell-libraries/lib_log.zsh
+
+# Avoids expressions like 'error here | true' to be executed
+set -o pipefail
+# List all executed lines. Usefull for debugging
+#set -o xtrace
+
+readonly PROGRAM_NAME="mess-cleaner"
+readonly PROJECT_ROOT="$HOME/dev/$PROGRAM_NAME"
+readonly CONFIG_FILE="$PROJECT_ROOT/modules.conf"
+
+class=""
+# Default mode is: rename file and create a directory
+mode=2
+
 usage() {
 	echo "$PROGRAM_NAME usage:\n"
 	echo "-f\tFile to rename"
@@ -15,20 +30,7 @@ echoerr() {
 	echo "$@" 1>&2
 }
 
-# Avoids expressions like 'error here | true' to be executed
-set -o pipefail
-# List all executed lines. Usefull for debugging
-#set -o xtrace
-
-readonly PROJECT_ROOT="$HOME/dev/mess-cleaner"
-readonly CONFIG_FILE="$PROJECT_ROOT/modules.conf"
-readonly PROGRAM_NAME="mess-cleaner"
-
-class=""
-# Default mode is: rename file and create a directory
-mode=2
-
-while getopts "f:hm:r" option; do
+while getopts "f:hm:rv" option; do
 	case "$option" in
 		f)
 			file_list+=($OPTARG)
@@ -43,6 +45,10 @@ while getopts "f:hm:r" option; do
 
 		r)
 			recursive=1
+			;;
+
+		v)
+			verbose_level=$(($verbose_level+1))
 			;;
 		*)
 			usage
@@ -61,8 +67,8 @@ if [[ $recursive -eq 1 ]]; then
 	relative_file_list=($(find . * | grep -P ".{2}[0-9]{4}_.*\/(c|i|ich)_.*"))
 
 	if [ ${#relative_file_list[@]} -eq 0 ]; then
-		echo "No files to be renamed"
-		echo "Exiting..."
+		.log $LOG_INFO "No files to be renamed"
+		.log $LOG_INFO "Exiting..."
 		exit 0
 	fi
 
@@ -78,7 +84,7 @@ for file in $file_list; do
 	cd $(dirname $file)
 	
 	if [[ -z "$file" ]]; then
-		echoerr "Missing options!\n"
+		.log LOG_ERR "Missing options!"
 		usage
 		exit 1
 	fi
@@ -93,20 +99,21 @@ for file in $file_list; do
 	grep $module_name $CONFIG_FILE -n 1>&2 /dev/null
 
 	if [ $? -eq 1 ]; then
-		echoerr "$module_name does not exist!"
+		.log LOG_ERR "$module_name does not exist!"
 		exit 1
 	fi
 
 	if [ ! -f "$file" ]; then
-		echoerr "File $file does not exit!"
+		.log LOG_ERR "File $file does not exist!"
 		exit 1
 	fi
 
 	if [[ ! $mode =~ '^[1-3]$' ]]; then
-		echoerr "The mode you entered is not valid"
-		echoerr "Enter a mode between 1 and 3"
+		.log LOG_ERR "The mode you entered is not valid!"
+		.log LOG_ERR "Enter a mode between 1 and 3"
 		exit 1
 	fi
+
 	class_name="INFO"
 	class_name+=$(grep $module_name $CONFIG_FILE -n | cut -f1 -d:)
 
@@ -122,20 +129,22 @@ for file in $file_list; do
 
 	case "$mode" in
 		1)
-			mkdir "$directory_name"
-			mv $file $file_name
-			mv $file_name $directory_name
+			mkdir "$directory_name" && .log LOG_INFO "Directory $directory_name successfully created"
+			mv $file $file_name && .log LOG_INFO "$file renamed to $file_name"
+			mv $file_name $directory_name && .log LOG_INFO "$file_name moved to $directory_name"
 			;;
 		2)
-			mv $file $file_name
+			mv $file $file_name && .log LOG_INFO "$file renamed to $file_name"
 			;;
 		3)
-			mkdir "$directory_name"
-			mv $file $directory_name
+			mkdir "$directory_name" && .log LOG_INFO "Directory $directory_name successfully created"
+			mv $file $directory_name && .log LOG_INFO "$file_name moved to $directory_name"
 			;;
 		*)
 			;;
 	esac
 done
+
+.log LOG_INFO "Exiting..."
 
 exit 0
